---
- hosts: all
  become: true
  tasks:

  - name: install php for ubuntu servers
    tags: ubuntu
    apt:
      name:
        - libapache2-mod-php
      state: latest
  - name: copy php file for site 
    tags: apache,apache,apache2
    copy:
      src: ~/play/index.php
      dest: /var/www/html/index.php
      owner: root
       group: root
      mode: 0644
  - name: set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos
  - name: print hostname on server
    tags: printf
    shell: echo "<h1>This is $(hostname -f) </h1>" > /var/www/html/index.html
  - name: restart apache2
    tags: restart
    service:
      name: apache2
      state: restarted